[package]
name = "nonempty-collections"
version = "0.1.0"
description = "Correct-by-construction non-empty collections."
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/fosskers/nonempty-collections"

[dependencies]
serde = { version = "1", features = ["serde_derive"], optional = true }

[dev-dependencies]
serde_json = "1"
